name: "License Check"

on:
  workflow_call:

jobs:
  licenseSearch:
    uses: ./.github/workflows/licensesearch.yml
    secrets: inherit
    with:
      commits: ${{ toJson(github.event.commits) }}

  handleFoundLicenses:
    needs: [licenseSearch]

    runs-on: ubuntu-latest
    
    steps:
      - name: Get number commits
        id: get_nr_commits
        if: ${{ needs.licenseSearch.outputs.filtered_results != '' }}
        env:
            commits: ${{ toJson(github.event.commits) }}
        run: |
            NUMBER_COMMITS=$(echo $commits | jq '. | length' )
            echo "number_commits=$NUMBER_COMMITS" >> $GITHUB_OUTPUT

      - name: Get push type
        id: push-type
        if: ${{ needs.licenseSearch.outputs.filtered_results != '' }}
        env: 
            COMMITCOUNT: ${{ steps.get_nr_commits.outputs.number_commits }}
        run: |
            echo "Getting push type"
            PUSH_TYPE='commit'
            FETCH_DEPTH=$(($COMMITCOUNT + 1))
            if ${{ github.event.before == '0000000000000000000000000000000000000000' }}; then
                PUSH_TYPE='branch'
                FETCH_DEPTH=0
            fi
            echo "Push type: $PUSH_TYPE"
            echo "Fetch depth: $FETCH_DEPTH"
            echo "push_type=$PUSH_TYPE" >> $GITHUB_OUTPUT
            echo "fetch_depth=$FETCH_DEPTH" >> $GITHUB_OUTPUT

      - name: Checkout
        if: ${{ needs.licenseSearch.outputs.filtered_results != '' }}
        uses: actions/checkout@v4
        with:
         fetch-depth: ${{ steps.push-type.outputs.fetch_depth }}

      - name: Remove commits if licenses found
        if: ${{ needs.licenseSearch.outputs.filtered_results != '' }}
        id: remove-license
        run: |
            info="$(jq -n --argjson data '[${{ steps.filter_results.outputs.filtered_results }}]' '"`" + $data[].commit + "`: " + $data[].licenselines')"
            echo info=$info >> $GITHUB_OUTPUT
            if ${{ steps.push-type.outputs.push_type == 'commit'}}; then
                git reset --hard HEAD~${{ steps.get_nr_commits.outputs.number_commits }}
                git push origin ${{ github.ref }} --force
                revertcommit="$(git rev-parse HEAD)"
                echo "Reverting to commit $revertcommit as newer commits contains licenses"
                echo "link=https://github.com/${{ github.repository }}/commits/${{ github.ref }}" >> $GITHUB_OUTPUT
                echo "short_msg=push denied, reset to '$revertcommit'!" >> $GITHUB_OUTPUT
                echo "action_type=reverted to" >> $GITHUB_OUTPUT
                echo "msg_code=$revertcommit" >> $GITHUB_OUTPUT
            else
                git push origin --delete ${{ github.ref }}
                echo "Removing branch ${{ github.ref }} as it contains licenses"
                echo "link=https://github.com/${{ github.repository }}/branches" >> $GITHUB_OUTPUT
                echo "short_msg='${{ github.ref }}' was removed!" >> $GITHUB_OUTPUT
                echo "action_type=removed" >> $GITHUB_OUTPUT
                echo "msg_code=${{ github.ref }}" >> $GITHUB_OUTPUT
            fi

      - name: Find correspondences
        id: email
        if: ${{ needs.licenseSearch.outputs.filtered_results != '' }}
        uses: slackapi/slack-github-action@v2.1.1
        with:
          method: users.lookupByEmail # https://api.slack.com/methods/users.lookupByEmail
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            email: ${{ github.event.pusher.email }}

      - name: Search email detail
        if: ${{ steps.email.outputs.ok }}
        run: |
          SLACK_USER_ID=$(echo '${{ steps.email.outputs.response }}' | jq -r '.user.id')
          echo "SLACK_USER_ID=$SLACK_USER_ID" >> $GITHUB_ENV

      - name: Send a direct message
        if: ${{ steps.email.outputs.ok }}
        uses: slackapi/slack-github-action@v2.1.1
        with:
          errors: true
          method: chat.postMessage # https://api.slack.com/methods/chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            "channel": "${{ env.SLACK_USER_ID }}",
            "text": "${{ steps.remove-license.outputs.short_msg }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":alert: *LICENSES DETECTED* :alert:"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ steps.remove-license.outputs.action_type}} ${{ steps.push-type.outputs.push_type}} `${{ steps.remove-license.outputs.msg_code }}`"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ${{ steps.remove-license.outputs.info}}
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<${{ steps.remove-license.outputs.link }}>"
                }
              }
            ]

      - name: Fallback Slack notification
        id: fallback_slack
        if: failure()
        uses: slackapi/slack-github-action@v2.1.1
        with:
          errors: true
          method: chat.postMessage # https://api.slack.com/methods/chat.postMessage
          token: ${{ secrets.SLACK_BOT_TOKEN }}
          payload: |
            "channel": "ci",
            "text": "${{ steps.remove-license.outputs.short_msg }}",
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":alert: *LICENSES DETECTED* :alert:"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "${{ steps.remove-license.outputs.action_type}} ${{ steps.push-type.outputs.push_type}} `${{ steps.remove-license.outputs.msg_code }}`"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ${{ steps.remove-license.outputs.info}}
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "<${{ steps.remove-license.outputs.link }}>"
                }
              }
            ]
